const NAMES_DB = {
  male: [
    { name: "Haruto", kanji: "陽翔", meaning: "Soaring sun" },
    { name: "Yuto", kanji: "勇斗", meaning: "Brave fighter" },
    { name: "Sota", kanji: "蒼太", meaning: "Vast blue sky" },
    { name: "Yuki", kanji: "勇樹", meaning: "Brave tree" },
    { name: "Hayato", kanji: "隼人", meaning: "Falcon person" },
    { name: "Kenji", kanji: "健二", meaning: "Healthy second son" },
    { name: "Ren", kanji: "蓮", meaning: "Lotus" },
    { name: "Takumi", kanji: "匠", meaning: "Artisan" },
    { name: "Kaito", kanji: "海斗", meaning: "Sea fighter" },
    { name: "Riku", kanji: "陸", meaning: "Land" },
    { name: "Shota", kanji: "翔太", meaning: "Soaring big" },
    { name: "Daiki", kanji: "大輝", meaning: "Great radiance" },
    { name: "Ryota", kanji: "涼太", meaning: "Cool and big" },
    { name: "Kenta", kanji: "健太", meaning: "Healthy and big" },
    { name: "Naoki", kanji: "直樹", meaning: "Honest tree" },
    { name: "Tatsuya", kanji: "達也", meaning: "Accomplished" },
    { name: "Makoto", kanji: "誠", meaning: "Sincerity" },
    { name: "Hiroshi", kanji: "寛", meaning: "Generous" },
    { name: "Kazuki", kanji: "一輝", meaning: "One radiance" },
    { name: "Tsubasa", kanji: "翼", meaning: "Wings" },
    { name: "Akira", kanji: "明", meaning: "Bright" },
    { name: "Isamu", kanji: "勇", meaning: "Courage" },
    { name: "Jiro", kanji: "次郎", meaning: "Second son" },
    { name: "Katsuro", kanji: "勝郎", meaning: "Victorious son" },
    { name: "Masaru", kanji: "勝", meaning: "Victory" },
    { name: "Nori", kanji: "典", meaning: "Rule, precedent" },
    { name: "Osamu", kanji: "修", meaning: "Discipline" },
    { name: "Raiden", kanji: "雷電", meaning: "Thunder and lightning" },
    { name: "Saburo", kanji: "三郎", meaning: "Third son" },
    { name: "Tadashi", kanji: "正", meaning: "Correct, loyal" },
    { name: "Takeshi", kanji: "武", meaning: "Military, warrior" },
    { name: "Tomio", kanji: "富雄", meaning: "Wealthy man" },
    { name: "Yasuo", kanji: "康男", meaning: "Peaceful man" },
    { name: "Yuichi", kanji: "雄一", meaning: "Heroic first son" },
    { name: "Zenji", kanji: "善二", meaning: "Good second son" },
    { name: "Fumio", kanji: "文夫", meaning: "Literary man" },
    { name: "Goro", kanji: "五郎", meaning: "Fifth son" },
    { name: "Hideki", kanji: "英樹", meaning: "Excellent tree" },
    { name: "Ichiro", kanji: "一郎", meaning: "First son" },
    { name: "Koji", kanji: "浩二", meaning: "Prosperous second son" },
  ],
  female: [
    { name: "Yui", kanji: "結衣", meaning: "Tie clothing" },
    { name: "Aoi", kanji: "葵", meaning: "Hollyhock" },
    { name: "Hina", kanji: "陽菜", meaning: "Sunny vegetables" },
    { name: "Rin", kanji: "凛", meaning: "Cold, dignified" },
    { name: "Sakura", kanji: "桜", meaning: "Cherry blossom" },
    { name: "Mio", kanji: "澪", meaning: "Water path" },
    { name: "Koharu", kanji: "心春", meaning: "Heart spring" },
    { name: "Akane", kanji: "茜", meaning: "Brilliant red" },
    { name: "Yuna", kanji: "由奈", meaning: "Reason, Nara" },
    { name: "Miku", kanji: "美空", meaning: "Beautiful sky" },
    { name: "Nana", kanji: "奈々", meaning: "Apple tree" },
    { name: "Saki", kanji: "咲", meaning: "Blossom" },
    { name: "Misaki", kanji: "美咲", meaning: "Beautiful blossom" },
    { name: "Ayaka", kanji: "彩花", meaning: "Colorful flower" },
    { name: "Noa", kanji: "乃愛", meaning: "Beloved" },
    { name: "Haruka", kanji: "遥", meaning: "Distant, far away" },
    { name: "Yuki", kanji: "雪", meaning: "Snow" },
    { name: "Reina", kanji: "玲奈", meaning: "Lovely Nara" },
    { name: "Kana", kanji: "佳奈", meaning: "Good Nara" },
    { name: "Mei", kanji: "芽衣", meaning: "Bud clothing" },
    { name: "Asuka", kanji: "明日香", meaning: "Tomorrow's fragrance" },
    { name: "Chika", kanji: "千佳", meaning: "A thousand blessings" },
    { name: "Emi", kanji: "笑美", meaning: "Smiling beauty" },
    { name: "Fumiko", kanji: "文子", meaning: "Child of literature" },
    { name: "Hanako", kanji: "花子", meaning: "Flower child" },
    { name: "Izumi", kanji: "泉", meaning: "Spring, fountain" },
    { name: "Junko", kanji: "純子", meaning: "Pure child" },
    { name: "Kazuko", kanji: "和子", meaning: "Harmonious child" },
    { name: "Kimiko", kanji: "君子", meaning: "Noble child" },
    { name: "Midori", kanji: "緑", meaning: "Green" },
    { name: "Naomi", kanji: "直美", meaning: "Straight beauty" },
    { name: "Noriko", kanji: "典子", meaning: "Child of precedent" },
    { name: "Ryoko", kanji: "涼子", meaning: "Cool child" },
    { name: "Sumiko", kanji: "澄子", meaning: "Clear child" },
    { name: "Tamiko", kanji: "民子", meaning: "People's child" },
    { name: "Tomoko", kanji: "友子", meaning: "Friendly child" },
    { name: "Yoshiko", kanji: "良子", meaning: "Good child" },
    { name: "Yukiko", kanji: "幸子", meaning: "Fortunate child" },
    { name: "Amaya", kanji: "雨夜", meaning: "Night rain" },
    { name: "Hoshi", kanji: "星", meaning: "Star" },
  ],
  family: [
    { name: "Sato", kanji: "佐藤", meaning: "Help wisteria" },
    { name: "Suzuki", kanji: "鈴木", meaning: "Bell tree" },
    { name: "Takahashi", kanji: "高橋", meaning: "High bridge" },
    { name: "Tanaka", kanji: "田中", meaning: "Rice field center" },
    { name: "Watanabe", kanji: "渡辺", meaning: "Cross the edge" },
    { name: "Ito", kanji: "伊藤", meaning: "That wisteria" },
    { name: "Yamamoto", kanji: "山本", meaning: "Mountain base" },
    { name: "Nakamura", kanji: "中村", meaning: "Middle village" },
    { name: "Kobayashi", kanji: "小林", meaning: "Small forest" },
    { name: "Kato", kanji: "加藤", meaning: "Add wisteria" },
    { name: "Yoshida", kanji: "吉田", meaning: "Lucky field" },
    { name: "Yamada", kanji: "山田", meaning: "Mountain rice field" },
    { name: "Sasaki", kanji: "佐々木", meaning: "Bamboo help tree" },
    { name: "Yamaguchi", kanji: "山口", meaning: "Mountain mouth" },
    { name: "Matsumoto", kanji: "松本", meaning: "Pine tree base" },
    { name: "Inoue", kanji: "井上", meaning: "Above the well" },
    { name: "Kimura", kanji: "木村", meaning: "Tree village" },
    { name: "Hayashi", kanji: "林", meaning: "Forest" },
    { name: "Shimizu", kanji: "清水", meaning: "Clear water" },
    { name: "Yamazaki", kanji: "山崎", meaning: "Mountain cape" },
    { name: "Fujiwara", kanji: "藤原", meaning: "Wisteria plain" },
    { name: "Ogawa", kanji: "小川", meaning: "Small river" },
    { name: "Nishimura", kanji: "西村", meaning: "West village" },
    { name: "Mori", kanji: "森", meaning: "Forest" },
    { name: "Maeda", kanji: "前田", meaning: "Before the rice field" },
    { name: "Fujita", kanji: "藤田", meaning: "Wisteria rice field" },
    { name: "Okamoto", kanji: "岡本", meaning: "Hill base" },
    { name: "Hashimoto", kanji: "橋本", meaning: "Bridge base" },
    { name: "Ishikawa", kanji: "石川", meaning: "Stone river" },
    { name: "Abe", kanji: "阿部", meaning: "Division" },
    { name: "Ueda", kanji: "上田", meaning: "Upper rice field" },
    { name: "Sakamoto", kanji: "坂本", meaning: "Hillside base" },
    { name: "Aoki", kanji: "青木", meaning: "Blue tree" },
    { name: "Miura", kanji: "三浦", meaning: "Three bays" },
    { name: "Fujii", kanji: "藤井", meaning: "Wisteria well" },
    { name: "Nishida", kanji: "西田", meaning: "West rice field" },
    { name: "Okada", kanji: "岡田", meaning: "Hill rice field" },
    { name: "Goto", kanji: "後藤", meaning: "Behind wisteria" },
    { name: "Hasegawa", kanji: "長谷川", meaning: "Long valley river" },
    { name: "Murata", kanji: "村田", meaning: "Village rice field" },
  ],
  city: [
    { name: "Akatsuki", kanji: "暁", meaning: "Dawn" },
    { name: "Shironami", kanji: "白波", meaning: "White wave" },
    { name: "Kuroyama", kanji: "黒山", meaning: "Black mountain" },
    { name: "Midorigawa", kanji: "緑川", meaning: "Green river" },
    { name: "Harukaze", kanji: "春風", meaning: "Spring breeze" },
    { name: "Tsukishiro", kanji: "月白", meaning: "Moonlit white" },
    { name: "Aokaze", kanji: "青風", meaning: "Blue wind" },
    { name: "Kageyama", kanji: "影山", meaning: "Shadow mountain" },
    { name: "Suzukaze", kanji: "涼風", meaning: "Cool breeze" },
    { name: "Taiyooka", kanji: "太陽丘", meaning: "Sun hill" },
    { name: "Hoshizora", kanji: "星空", meaning: "Starry sky" },
    { name: "Umikaze", kanji: "海風", meaning: "Sea breeze" },
    { name: "Kirishima", kanji: "霧島", meaning: "Fog island" },
    { name: "Yoakemura", kanji: "夜明村", meaning: "Dawn village" },
    { name: "Fujioka", kanji: "富士岡", meaning: "Fuji hill" },
    { name: "Aoyama", kanji: "青山", meaning: "Blue mountain" },
    { name: "Sakuragawa", kanji: "桜川", meaning: "Cherry blossom river" },
    { name: "Tokinoshima", kanji: "時の島", meaning: "Island of time" },
    { name: "Kumomori", kanji: "雲森", meaning: "Cloud forest" },
    { name: "Ryugasaki", kanji: "龍ヶ崎", meaning: "Dragon cape" },
    { name: "Kazakami", kanji: "風上", meaning: "Windward" },
    { name: "Shirokawa", kanji: "白川", meaning: "White river" },
    { name: "Nagaredani", kanji: "流れ谷", meaning: "Flowing valley" },
    { name: "Mizuhara", kanji: "水原", meaning: "Water plain" },
    { name: "Takegawa", kanji: "竹川", meaning: "Bamboo river" },
  ],
  clan: [
    { name: "Oda", kanji: "織田", meaning: "Woven rice field" },
    { name: "Tokugawa", kanji: "徳川", meaning: "Virtue river" },
    { name: "Takeda", kanji: "武田", meaning: "Warrior rice field" },
    { name: "Uesugi", kanji: "上杉", meaning: "Upper cedar" },
    { name: "Shimazu", kanji: "島津", meaning: "Island harbor" },
    { name: "Mori", kanji: "毛利", meaning: "Hair profit" },
    { name: "Chosokabe", kanji: "長宗我部", meaning: "Long ancestral part" },
    { name: "Hojo", kanji: "北条", meaning: "North article" },
    { name: "Imagawa", kanji: "今川", meaning: "Present river" },
    { name: "Date", kanji: "伊達", meaning: "That achievement" },
    { name: "Sanada", kanji: "真田", meaning: "True rice field" },
    { name: "Asai", kanji: "浅井", meaning: "Shallow well" },
    { name: "Asakura", kanji: "朝倉", meaning: "Morning storehouse" },
    { name: "Miyoshi", kanji: "三好", meaning: "Three goods" },
    { name: "Rokkaku", kanji: "六角", meaning: "Six corners" },
    { name: "Otomo", kanji: "大友", meaning: "Great friend" },
    { name: "Ryuzoji", kanji: "龍造寺", meaning: "Dragon creation temple" },
    { name: "Amako", kanji: "尼子", meaning: "Nun child" },
    { name: "Kitabatake", kanji: "北畠", meaning: "North field" },
    { name: "Hatakeyama", kanji: "畠山", meaning: "Field mountain" },
  ]
};
